services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: 'Elml0110!?123'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'mydatabase'
      MYSQL_ROOT_HOST: '0.0.0.0/0'
    volumes:
      - 'db-volume:/var/lib/mysql'
    ports:
      - '3306:3306'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
    build:
      context: '.'
      dockerfile: 'db/Dockerfile'
  web:
    depends_on:
      - 'db'
    ports:
      - '8080:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Remote/web/Dockerfile'
volumes:
  db-volume: ~
